# Generated by Django 3.2.9 on 2021-12-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_tables',
            name='phone',
        ),
        migrations.AddField(
            model_name='register_tables',
            name='avt',
            field=models.ImageField(default=None, upload_to='media/avatar'),
        ),
    ]
