# Generated by Django 3.2.9 on 2021-12-09 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211207_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_tables',
            name='avt',
            field=models.ImageField(blank=True, default=None, upload_to='media/avatar'),
        ),
    ]
