# Generated by Django 3.2.9 on 2021-12-09 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_register_tables_avt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_tables',
            name='avt',
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avt', models.ImageField(blank=True, default=None, upload_to='media/avatar')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login.register_tables')),
            ],
        ),
    ]
