# Generated by Django 2.2.1 on 2021-12-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camnang2',
            fields=[
                ('camnang_id', models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('camnang_name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=100)),
                ('view', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('description', models.CharField(default='', max_length=200)),
                ('bg', models.ImageField(default=None, upload_to='camnang_img')),
                ('link', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
