# Generated by Django 2.2.1 on 2021-12-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camnang', '0002_auto_20211212_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id_cn',
            field=models.CharField(default='', max_length=200),
        ),
    ]
