# Generated by Django 2.2.1 on 2021-12-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camnang', '0003_auto_20211212_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
