# Generated by Django 2.2.1 on 2021-12-18 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hotel_id', models.CharField(default='', max_length=200)),
                ('hname', models.CharField(default='', max_length=500)),
                ('locate', models.CharField(default='', max_length=100)),
                ('room_type', models.CharField(default='', max_length=500)),
                ('check_in', models.DateField(default='')),
                ('check_out', models.DateField(default='')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('cmnd', models.CharField(default='', max_length=100)),
                ('pay', models.CharField(default='', max_length=100)),
                ('mess', models.TextField(default='', null=True)),
                ('total_price', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
