# Generated by Django 2.2.1 on 2021-12-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='quanti',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
