# Generated by Django 2.2.1 on 2021-12-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_auto_20211219_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mess',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
