# Generated by Django 2.2.1 on 2021-12-19 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_booking_book_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='mess',
        ),
    ]
